from object.test import TestBase
from object.test import TestBat
from object.test import TestBG
from object.test import TestBullet
from object.test import TestGoal
from object.test import TestGroup
from object.test import TestMachine
from object.test import TestObject
from object.test import TestText
from object.test import TestTitle
from object.test import TitleGroup
from object.test import TitleText1
from object.test import TitleText2
